language: go

sudo: required

go:
  - 1.8

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

before_script:
  - glide install
  - go vet $(go list ./... | grep -v /vendor/)

script: go test $(go list ./... | grep -v /vendor/)